//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroCliente
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabCliente
    {
        public int codigo { get; set; }
        public long CNPJ { get; set; }
        public string razaoSocial { get; set; }
        public string endereco { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string uf { get; set; }
        public int CEP { get; set; }
    }
}
